create:
	./scripts/create.sh

start:
	./scripts/start.sh

stop:
	./scripts/stop.sh

status:
	./scripts/status.sh

drop:
	./scripts/drop.sh

clean:
	./scripts/clean.sh

psql:
	psql -U ${DBUSER} -d ${DBNAME}
