\i sql/account.sql
\i sql/ledger.sql
\i sql/actor.sql
\i sql/offert.sql
\i sql/address.sql
\i sql/billing.sql
\i sql/payment.sql
\i sql/cash.sql
\i sql/product.sql
\i sql/catalog.sql
\i sql/provider.sql
\i sql/charge.sql
\i sql/service.sql
\i sql/customer.sql
\i sql/subscriptiob.sql
\i sql/cycle.sql
\i sql/subscription_history.sql
\i sql/event.sql
\i sql/tax.sql
\i sql/fee.sql
\i sql/usage.sql
\i sql/invoice.sql
\i sql/user.sql
\i sql/label.sql
